idf_component_register(
    SRCS
        "main.c"
        "app/radar_app.c"
        "app/radar_controller.c"
        "board/waveshare_display_port.c"
        "config/radar_config.c"
        "data/airport_data.c"
        "data/coastline_data.c"
        "hardware/radar_haptics.c"
        "network/radar_network.c"
        "ui/radar_display.c"
    INCLUDE_DIRS
        "app"
        "board"
        "config"
        "data"
        "hardware"
        "model"
        "network"
        "ui"
    REQUIRES
        cjson
        esp_event
        esp_http_client
        esp_http_server
        esp_netif
        esp_wifi
        esp_lcd_sh8601
        i2c_bsp
        lcd_bl_pwm_bsp
        lcd_touch_bsp
        lvgl
        mbedtls
        mdns
        nvs_flash
        user_encoder_bsp)
