#!/usr/bin/env python3
"""Generate the compact scheduled-airport table used by the firmware."""

import argparse
import csv
import io
import pathlib
import re
import urllib.request


DEFAULT_SOURCE = "https://davidmegginson.github.io/ourairports-data/airports.csv"
CODE_PATTERN = re.compile(r"^[A-Z0-9]{2,4}$")


def read_source(source: str) -> str:
    path = pathlib.Path(source)
    if path.is_file():
        return path.read_text(encoding="utf-8-sig")
    with urllib.request.urlopen(source, timeout=60) as response:
        return response.read().decode("utf-8-sig")


def airport_code(row: dict[str, str]) -> str:
    for field in ("iata_code", "icao_code", "gps_code", "ident"):
        code = row.get(field, "").strip().upper()
        if CODE_PATTERN.fullmatch(code):
            return code
    return ""


def load_airports(csv_text: str) -> list[tuple[float, float, str]]:
    airports: list[tuple[float, float, str]] = []
    seen: set[tuple[str, float, float]] = set()
    for row in csv.DictReader(io.StringIO(csv_text)):
        if row.get("scheduled_service", "").lower() != "yes":
            continue
        if row.get("type", "").lower() == "closed":
            continue
        code = airport_code(row)
        if not code:
            continue
        try:
            latitude = float(row["latitude_deg"])
            longitude = float(row["longitude_deg"])
        except (KeyError, TypeError, ValueError):
            continue
        key = (code, round(latitude, 6), round(longitude, 6))
        if key in seen:
            continue
        seen.add(key)
        airports.append((latitude, longitude, code))
    airports.sort(key=lambda airport: (airport[2], airport[0], airport[1]))
    return airports


def write_c_file(output: pathlib.Path,
                 airports: list[tuple[float, float, str]]) -> None:
    lines = [
        "/* Generated by tools/generate_airport_data.py from OurAirports data. */",
        '#include "airport_data.h"',
        "",
        "const radar_airport_t radar_airports[] =",
        "{",
    ]
    lines.extend(
        f'    {{{latitude:.6f}f, {longitude:.6f}f, "{code}"}},'
        for latitude, longitude, code in airports
    )
    lines.extend(
        [
            "};",
            "",
            "const size_t radar_airport_count =",
            "    sizeof(radar_airports) / sizeof(radar_airports[0]);",
            "",
        ]
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", default=DEFAULT_SOURCE,
                        help="OurAirports CSV URL or a local airports.csv file")
    parser.add_argument("--output", default="main/data/airport_data.c")
    args = parser.parse_args()

    airports = load_airports(read_source(args.source))
    if not airports:
        raise SystemExit("No scheduled airports found in input data")
    output = pathlib.Path(args.output)
    write_c_file(output, airports)
    print(f"Generated {len(airports)} airports in {output}")


if __name__ == "__main__":
    main()
