#!/usr/bin/env python3
"""Generate compact coastline vectors for the firmware from Natural Earth."""

import argparse
import json
import pathlib
import urllib.request


DEFAULT_SOURCE = (
    "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/"
    "master/geojson/ne_50m_coastline.geojson"
)
COORDINATE_SCALE = 10_000


def read_source(source: str) -> dict:
    path = pathlib.Path(source)
    if path.is_file():
        return json.loads(path.read_text(encoding="utf-8"))
    with urllib.request.urlopen(source, timeout=60) as response:
        return json.load(response)


def geometry_lines(geometry: dict) -> list[list[list[float]]]:
    geometry_type = geometry.get("type")
    coordinates = geometry.get("coordinates", [])
    if geometry_type == "LineString":
        return [coordinates]
    if geometry_type == "MultiLineString":
        return coordinates
    return []


def load_paths(document: dict) -> list[list[tuple[int, int]]]:
    paths: list[list[tuple[int, int]]] = []
    for feature in document.get("features", []):
        for line in geometry_lines(feature.get("geometry") or {}):
            points: list[tuple[int, int]] = []
            for coordinate in line:
                if len(coordinate) < 2:
                    continue
                longitude = round(float(coordinate[0]) * COORDINATE_SCALE)
                latitude = round(float(coordinate[1]) * COORDINATE_SCALE)
                point = (latitude, longitude)
                if not points or points[-1] != point:
                    points.append(point)
            if len(points) >= 2:
                paths.append(points)
    return paths


def write_c_file(output: pathlib.Path,
                 paths: list[list[tuple[int, int]]]) -> None:
    points = [point for path in paths for point in path]
    lines = [
        "/* Generated by tools/generate_coastline_data.py from Natural Earth. */",
        '#include "coastline_data.h"',
        "",
        "const radar_geo_point_t radar_coastline_points[] =",
        "{",
    ]
    lines.extend(f"    {{{latitude}, {longitude}}},"
                 for latitude, longitude in points)
    lines.extend(["};", "", "const size_t radar_coastline_point_count =",
                  "    sizeof(radar_coastline_points) / sizeof(radar_coastline_points[0]);",
                  "", "const radar_coastline_path_t radar_coastline_paths[] =", "{"])
    first_point = 0
    for path in paths:
        lines.append(f"    {{{first_point}, {len(path)}}},")
        first_point += len(path)
    lines.extend(["};", "", "const size_t radar_coastline_path_count =",
                  "    sizeof(radar_coastline_paths) / sizeof(radar_coastline_paths[0]);",
                  ""])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", default=DEFAULT_SOURCE,
                        help="Natural Earth GeoJSON URL or local file")
    parser.add_argument("--output", default="main/data/coastline_data.c")
    args = parser.parse_args()

    paths = load_paths(read_source(args.source))
    if not paths:
        raise SystemExit("No coastline paths found in input data")
    write_c_file(pathlib.Path(args.output), paths)
    print(f"Generated {len(paths)} paths with "
          f"{sum(len(path) for path in paths)} points in {args.output}")


if __name__ == "__main__":
    main()
